<ClockLabel@Label>:
    font_size: 120
    size: self.texture_size
    font_name: "../assets/fonts/alarm-clock.ttf"
    # color: 0, 0, 0, 1
    # size: 150, 50
    # background_normal: ''
    # background_down: 'bkgrd-down-color.png'
    # background_color: .88, .88, .88, 1

<ClockFace>:
	ClockLabel:
		id: clock
    	text: '00:00:00'
    	# pos: root.width / 2 + self.width / 2, 200
    	pos: root.center_x - self.width /2, root.center_y - self.height / 2